create destination & improvements
conduitio-labs/conduit-connector-http pull request #17
Opened 2024-03-29 20:14 UTC by maha-hajja

### Description

### Quick checks:

- [ ] There is no other [pull request](https://github.com/conduitio-labs/conduit-connector-http/pulls) for the same update/change.
- [ ] I have written unit tests.
- [ ] I have made sure that the PR is of reasonable size and can be easily reviewed.

2024-04-01 16:11 UTC, raulb reviewed
Code looks great. Just one comment on the design for `Params`

2024-04-01 16:11 UTC, raulb commented on README.md
> +| `params`        | parameters to use in the request, & separated list of = separated pairs.            | false    |               |
@maha-hajja I personally think we should follow use them comma separated (since that's what I think we generally do when sending several attributes to a key), and then use `&` in the code. In other words, make it intuitive to the use. What do you think?

2024-04-01 18:59 UTC, maha-hajja commented on README.md
> +| `params`        | parameters to use in the request, & separated list of = separated pairs.            | false    |               |
Haris had the same comment on the other PR https://github.com/conduitio-labs/conduit-connector-http/pull/2#discussion_r1196126034 , so I made the change 👀

2024-04-02 10:18 UTC, raulb commented on README.md
> +| `params`        | parameters to use in the request, & separated list of = separated pairs.            | false    |               |
@maha-hajja oh, great, thank you!

2024-04-02 10:38 UTC, raulb requested changes
Just a tweak on the parameter configuration. Otherwise, looks good

2024-04-02 10:38 UTC, raulb commented on config.go
> +			s.URL += s.Params
@maha-hajja I'd imagine that if `s.URL` already contains a `?`, this means there's already a parameter there which means we'd also need to concat a `&` at the beginning, otherwise, it'd be something like `url?p=vp2=2&p3=v3`. 

This is a way we could ensure either option works. Let me know what you think https://go.dev/play/p/pxOH35ip_QR

2024-04-02 17:45 UTC, maha-hajja commented on config.go
> +			s.URL += s.Params
@raulb why not just change this line to `s.URL += "&"+ s.Params`?

2024-04-02 22:18 UTC, maha-hajja commented on config.go
> +			s.URL += s.Params
I pushed the simple fix with a new test, lemme know what you think

2024-04-03 09:35 UTC, raulb commented on config.go
> +			s.URL += s.Params
> @raulb nice catch! but why not just change this line to `s.URL += "&"+ s.Params`?

@maha-hajja to be sure the URL is correctly formatted. Otherwise, it could be something like `https://my-url.com?&`

2024-04-03 17:10 UTC, maha-hajja commented on config.go
> +			s.URL += s.Params
@raulb oooh I see.. updated :D

2024-04-04 12:11 UTC, raulb approved these changes
@maha-hajja looks great. Thank you for making those changes. I only suggested a change to the README as it seems `POST` is the default value for destination connectors. Great work!

2024-04-04 12:11 UTC, raulb commented on README.md
> +| `method`  | Http method to use in the request, supported methods are (`POST`,`PUT`,`DELETE`,`PATCH`). | false      | `GET`         |
```suggestion
| `method`  | Http method to use in the request, supported methods are (`POST`,`PUT`,`DELETE`,`PATCH`). | false      | `POST`         |
```

2024-04-04 16:02 UTC, maha-hajja commented on README.md
> +| `method`  | Http method to use in the request, supported methods are (`POST`,`PUT`,`DELETE`,`PATCH`). | false      | `GET`         |
another good catch!

2024-04-04 16:23 UTC, lovromazgon commented on README.md
> +| `method`  | Http method to use in the request, supported methods are (`POST`,`PUT`,`DELETE`,`PATCH`). | false      | `GET`         |
That's why we need a generated readme for connectors based on the specifications 🙃

2024-04-04 19:09 UTC, merged

2024-04-08 12:56 UTC, lovromazgon commented on README.md
> +| `method`  | Http method to use in the request, supported methods are (`POST`,`PUT`,`DELETE`,`PATCH`). | false      | `GET`         |
FWIW, I experimented on this over the weekend, here's the draft https://github.com/ConduitIO/conduit-connector-sdk/pull/115